server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
        # Ruta para el Servicio de Bancos
        - id: bank-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/banks/**

        # Ruta para el Servicio de Cuentas
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/accounts/**

jwt:
  secret: 09879856YNB6B824H5JLKSGKLNKLDASJGFBNSD87254ljkhs