server:
  port: 8080

spring:
  application:
    name: api-gateway

jwt:
  secret: 09879856YNB6B824H5JLKSGKLNKLDASJGFBNSD87254ljkhs

services:
  uris:
    bank-service: http://localhost:8081
    account-service: http://localhost:8082
    security-service: http://localhost:8086

routes:
  bank-service:
    id: bank_service_route
    path: /api/v1/banks/**
  account-service:
    id: account_service_route
    path: /api/v1/accounts/**
  security-service:
    id: auth-service
    path: /api/auth/**
