server:
  port: 8084

spring:
  application:
    name: transfer-service
  
  # Configuración para la conexión a RabbitMQ como consumidor
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  # Configuración para la base de datos propia de este servicio
  h2:
    console:
      enabled: true
      path: /h2-console-transfers

  r2dbc:
    url: r2dbc:h2:mem:///transferdb
    username: sa
    password: ''

  sql:
    init:
      mode: always