server:
  port: 8082

spring:
  application:
    name: account-service
  
  h2:
    console:
      enabled: true
      path: /h2-console-accounts

  r2dbc:
    url: r2dbc:h2:mem:///accountdb
    username: sa
    password: ''

  sql:
    init:
      mode: always

bank:
  service:
    url: http://localhost:8081
